public  class address {
   public void homeAddress(){
    string name =' Tim TT';
    system.debug('This is Name ' + name);
    Integer familyMember=4;
    system.debug('family Member ' + familyMember);
    String houseName='TDR';
    system.debug( 'Haouse Name :' + houseName);
    Integer houseNumber=164;
    system.debug('164');
    string streetName='Brighton rd';
    system.debug('Street Name: ' + streetName);
    string cityName='Clifton';
    system.debug('City : ' + cityName);
    string state='NJ';
    system.debug('State :' + state);
    string stateIso='NJ-USA';
    system.debug('State ISO :' +stateIso);
    string country='USA';
    system.debug(' Country :' + country);
    string countryIso='USA';
    system.debug('Country ISO :' + countryIso);
    integer zippCode=07064;
    system.debug(' Zipp Code :' + zippCode);
    boolean isyourHome = true;
    system.debug( 'is Your Home : ' +isyourHome);
    
    
   }
}
